version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

orbs:
  win: circleci/windows@4.1.1

jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - restore_cache:
          keys: sdks-and-tools-v2
      - run:
          name: "Install WiX Toolset"
          command: choco upgrade wixtoolset
      - run:
          name: "Install JDK"
          command: choco upgrade microsoft-openjdk
      - run:
          name: "Gradle Copy Wrapper"
          command: .\gradlew --parallel --no-daemon --dependency-verification lenient copyWrapper
      - run:
          name: "Gradle Package"
          command: .\gradlew --parallel --no-daemon --dependency-verification lenient package
      - save_cache:
          key: sdks-and-tools-v2
          paths:
            - C:\users\circleci\appdata\local\temp\chocolatey

workflows:
  # This workflow is set to be conditionally triggered,
  # only via the GitHub Action.
  # With no other unfiltered workflows, normal push events will be ignored.
  when: << pipeline.parameters.GHA_Action >>
  package:
    jobs:
      - build