version: 2.1

orbs:
  win: circleci/windows@4.1.1

jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - restore_cache:
          keys: sdks-and-tools
      - run:
          name: "Install WiX Toolset"
          command: choco upgrade wixtoolset
      - run:
          name: "Install JDK"
          command: choco upgrade microsoft-openjdk
      - run:
          name: "Write gradle properties"
          command: '"org.gradle.dependency.verification=lenient`norg.gradle.parallel=true" | Out-File -FilePath .\gradle.properties'
      - run:
          name: "Gradle Package"
          command: .\gradlew package
      - save_cache:
          key: sdks-and-tools
          paths:
            - C:\ProgramData\chocolatey\lib
