name: package
on: [ workflow_dispatch, push ]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 17
          cache: gradle
          architecture: x64
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Gradle Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --scan --parallel --dependency-verification lenient test
      - name: Gradle copyWrapper
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --scan --parallel --dependency-verification lenient copyWrapper
      - name: Gradle package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --scan --parallel --dependency-verification lenient package
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows Installer x64
          path: build/wix/OldenetInstaller.msi
